tsjrequests/tsj/urls.py
from django.urls import path
from . import views
from .views import AjaxUpdateView

urlpatterns = [
    path('', views.show_requests, name='home'),
    path('workers/', views.show_workers, name='workers'),
    path('residents/', views.show_residents, name='residents'),
    path('requests/', views.show_requests, name='requests'),
    path('apartments/', views.show_apartments, name='apartments'),
    path('addresses/', views.show_addresses, name='addresses'),
    # path('requests/<int:req_id>', views.show_request, name='request'),
    path('requests/<slug:type_slug>', views.show_request_by_type, name='request_type'),
    path('create-address/', views.update_address, name='create_address'),
    path('update-address/<int:address_id>', views.update_address, name='update_address'),
    path('delete-address/<int:address_id>', views.delete_address, name='delete_address'),
    path('create-worker/', views.update_worker, name='create_worker'),
    path('update-worker/<int:worker_id>', views.update_worker, name='update_worker'),
    path('delete-worker/<int:worker_id>', views.delete_worker, name='delete_worker'),
    path('create-request/', views.update_request, name='create_request'),
    path('update-request/<int:request_id>', views.update_request, name='update_request'),
    path('delete-request/<int:request_id>', views.delete_request, name='delete_request'),
    path('create-resident/', views.update_resident, name='create_resident'),
    path('update-resident/<int:resident_id>', views.update_resident, name='update_resident'),
    path('delete-resident/<int:resident_id>', views.delete_resident, name='delete_resident'),
    path('create-apartment/', views.update_apartment, name='create_apartment'),
    path('update-apartment/<int:apartment_id>', views.update_apartment, name='update_apartment'),
    path('delete-apartment/<int:apartment_id>', views.delete_apartment, name='delete_apartment'),
    path('workers/<slug:position_slug>', views.show_worker_by_position, name='worker_position'),
    path('work-types/<int:work_position_id>', views.show_work_types, name='home'),
    path('ajax-update/', AjaxUpdateView.as_view(), name='ajax_update')
]

tsjrequests/tsjrequests/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tsj.urls')),
]

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Заявки ТСЖ"

tsjrequests/tsj/models.py
from django.db import models
from django.urls import reverse


class Request(models.Model):
    work_type = models.ForeignKey('WorkType', on_delete=models.PROTECT, verbose_name="Тип услуги")
    worker = models.ForeignKey('Worker', on_delete=models.PROTECT, null=True, verbose_name="Работник")
    resident = models.ForeignKey('Resident', on_delete=models.PROTECT, verbose_name="Житель")
    address = models.ForeignKey('Address', on_delete=models.PROTECT, verbose_name="Адрес", blank=True)
    apartment = models.ForeignKey('Apartment', on_delete=models.PROTECT, verbose_name="Квартира")
    status = models.ForeignKey('Status', on_delete=models.PROTECT, default=1, verbose_name="Статус")
    request_type = models.ForeignKey('RequestType', on_delete=models.PROTECT, verbose_name="Тип заявки")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")
    update_time = models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления")
    description = models.TextField(null=True, blank=True, verbose_name="Описание")

    def __str__(self):
        return f"Заявка на {self.work_type} по адресу: {self.address}"

    def get_absolute_url(self):
        return reverse('update_request', kwargs={'request_id': self.pk})

    class Meta:
        ordering = ['pk']


class RequestType(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title


class Worker(models.Model):
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    phone_number = models.CharField(max_length=255, null=True, verbose_name="Номер телефона", blank=True)
    work_position = models.ForeignKey('WorkPosition', on_delete=models.PROTECT, verbose_name="Должность")
    # work_types = models.ManyToManyField('WorkType')

    class Meta:
        verbose_name = "Работник"
        verbose_name_plural = "Работники"
        ordering = ['pk']

    def __str__(self):
        return f"{self.first_name} {self.last_name}, {self.work_position}"

    def get_absolute_url(self):
        return reverse('update_worker', kwargs={'worker_id': self.pk})


class Resident(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    # address = models.ForeignKey('Address', on_delete=models.PROTECT)
    apartment = models.ForeignKey('Apartment', on_delete=models.PROTECT)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('update_resident', kwargs={'resident_id': self.pk})


class WorkType(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Стоимость")
    description = models.TextField(null=True, verbose_name="Описание")
    work_position = models.ForeignKey('WorkPosition', on_delete=models.PROTECT, verbose_name="Должность")
    request_type = models.ForeignKey('RequestType', on_delete=models.PROTECT, verbose_name="Тип заявки")

    class Meta:
        verbose_name = "Тип работы"
        verbose_name_plural = "Типы работ"
        ordering = ['pk']

    def __str__(self):
        return self.title


class Status(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Address(models.Model):
    street_name = models.CharField(max_length=255)
    house_number = models.IntegerField()

    class Meta:
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"
        ordering = ['pk']

    def __str__(self):
        return f"{self.street_name}, дом {self.house_number}"

    def get_absolute_url(self):
        return reverse('update_address', kwargs={'address_id': self.pk})

    def as_dict(self):
        address = {
            'id': self.pk,
            'street-name': self.street_name,
            'house-number': self.house_number,
        }
        return address


class Apartment(models.Model):
    number = models.IntegerField()
    address = models.ForeignKey('Address', on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Квартира"
        verbose_name_plural = "Квартиры"
        ordering = ['pk']

    def __str__(self):
        return f"{self.address}, кв. {self.number}"

    def get_absolute_url(self):
        return reverse('update_apartment', kwargs={'apartment_id': self.pk})

    def as_dict(self):
        apartment = {
            'id': self.pk,
            'number': self.number,
            'address': Address.as_dict(self.address),
        }
        return apartment


class WorkPosition(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True)
    slug = models.SlugField(max_length=255)

    class Meta:
        verbose_name = "Должность"
        verbose_name_plural = "Должности"
        ordering = ['pk']

    def __str__(self):
        return self.title

tsjrequests/tsj/views.py
import json

from django.core.paginator import Paginator
from django.db.models import Max
from django.http import HttpResponse, JsonResponse, QueryDict
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.core.serializers import serialize

from tsj.forms import AddAddressForm, AddWorkerForm, AddRequestForm, AddApartmentForm, AddResidentForm
from tsj.models import WorkType, WorkPosition, Address, Worker, Apartment, Resident, Request, Status, RequestType

menu = [
    {'title': "Работники", 'url_name': "workers"},
    {'title': "Жители", 'url_name': "residents"},
    {'title': "Заявки", 'url_name': "requests"},
    {'title': "Адреса", 'url_name': "addresses"},
    {'title': "Квартиры", 'url_name': "apartments"},
]

errors = {
    'wrong_position_error': "ошибка, специализация работника не соответствует типу услуги",
    'wrong_request_type': "ошибка, тип заявки не соответствует типу услуги",
    'wrong_request_status': "неправильно выбран статус заявки",
    'wrong_apartment': "выбрана неправильная квартира",
}

# не заработало
class AjaxUpdateView(View):
    def get(self, request, *args, **kwargs):
        address = request.GET.get('apartment', None)
        if address:
            data = Apartment.objects.filter(address_id=address)
            serialized_data = serialize('json', data)
            print(data)
            apartments = [Apartment.as_dict(item) for item in data]
            print(serialized_data)
            return JsonResponse({'apartment': serialized_data})
        return JsonResponse({'apartment': []})


def index(request):
    data = {
        'title': 'Главная страница информационного портала ТСЖ "Солнышко"',
        'menu': menu,
    }
    return render(request, 'tsj/index.html', context=data)


def show_workers(request):
    workers = Worker.objects.all()
    number_of_workers = Worker.objects.count()
    data = {
        'title': 'Работники',
        'menu': menu,
        'items': workers,
        'number': number_of_workers,
    }
    return render(request, 'tsj/list_workers.html', context=data)


def show_residents(request):
    residents = Resident.objects.all()
    number_of_residents = Resident.objects.count()
    data = {
        'title': 'Зарегистрированные жители',
        'menu': menu,
        'items': residents,
        'number': number_of_residents,
    }
    return render(request, 'tsj/list_residents.html', context=data)


def show_requests(request):
    requests = Request.objects.all()
    number_of_requests = Request.objects.count()
    max_price = WorkType.objects.aggregate(Max('price'))
    data = {
        'title': 'Все заявки',
        'menu': menu,
        'items': requests,
        'number': number_of_requests,
        'max_price': max_price['price__max']
    }
    return render(request, 'tsj/list_requests.html', context=data)


def show_request_by_type(request, type_slug):
    type = get_object_or_404(RequestType, slug=type_slug)
    requests = Request.objects.filter(request_type_id=type.pk)
    number_of_requests = requests.count()
    data = {
        'title': f"Заявки типа: {type.title}",
        'menu': menu,
        'items': requests,
        'number': number_of_requests,
    }
    return render(request, 'tsj/list_requests.html', context=data)


def show_worker_by_position(request, position_slug):
    position = get_object_or_404(WorkPosition, slug=position_slug)
    workers = Worker.objects.filter(work_position_id=position.pk)
    number_of_workers = workers.count()
    data = {
        'title': f"Работники по специальности: {position.title}",
        'menu': menu,
        'items': workers,
        'number': number_of_workers,
    }
    return render(request, 'tsj/list_workers.html', context=data)


def update_request(request, request_id=None):
    if request_id is not None:
        instance = Request.objects.get(pk=request_id)
    else:
        instance = None
    if request.method == 'POST':
        form = AddRequestForm(request.POST, instance=instance)
        if form.is_valid():
            status = form.cleaned_data['status']
            work_type = form.cleaned_data['work_type']
            worker = form.cleaned_data['worker']
            request_type = form.cleaned_data['request_type']
            address = form.cleaned_data['address']
            apartment = form.cleaned_data['apartment']
            if worker.work_position != work_type.work_position:
                form.add_error('worker', errors['wrong_position_error'])
            if request_type.pk != work_type.request_type_id:
                form.add_error('request_type', errors['wrong_request_type'])
            if worker is not None and (status.pk == 1 or status.pk == 5):
                form.add_error('status', errors['wrong_request_status'])
            if apartment.address != address:
                form.add_error('apartment', errors['wrong_apartment'])
            if form.is_valid():
                form.save()
                return redirect('requests')
        else:
            form.add_error(None, "ошибка")
    else:
        form = AddRequestForm(instance=instance)
    data = {
        'menu': menu,
        'title': 'Добавить/изменить заявку',
        'form': form,
    }
    return render(request, 'tsj/create.html', data)


def update_address(request, address_id=None):
    if address_id is not None:
        instance = Address.objects.get(pk=address_id)
    else:
        instance = None
    if request.method == 'POST':
        form = AddAddressForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('addresses')
        else:
            form.add_error(None, "ошибка")
    else:
        form = AddAddressForm(instance=instance)

    data = {
        'menu': menu,
        'title': 'Добавить/изменить адрес',
        'form': form,
    }
    return render(request, 'tsj/create.html', data)


def update_worker(request, worker_id=None):
    if worker_id is not None:
        instance = Worker.objects.get(pk=worker_id)
    else:
        instance = None
    if request.method == 'POST':
        form = AddWorkerForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('workers')
        else:
            form.add_error(None, "ошибка")
    else:
        form = AddWorkerForm(instance=instance)

    data = {
        'menu': menu,
        'title': 'Добавить/изменить адрес',
        'form': form,
    }
    return render(request, 'tsj/create.html', data)


def update_resident(request, resident_id=None):
    if resident_id is not None:
        instance = Resident.objects.get(pk=resident_id)
    else:
        instance = None
    if request.method == 'POST':
        form = AddResidentForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('residents')
        else:
            form.add_error(None, "ошибка")
    else:
        form = AddResidentForm(instance=instance)

    data = {
        'menu': menu,
        'title': 'Добавить/изменить жителя',
        'form': form,
    }
    return render(request, 'tsj/create.html', data)


def update_apartment(request, apartment_id=None):
    if apartment_id is not None:
        instance = Apartment.objects.get(pk=apartment_id)
    else:
        instance = None
    if request.method == 'POST':
        form = AddApartmentForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('apartments')
        else:
            form.add_error(None, "ошибка")
    else:
        form = AddApartmentForm(instance=instance)

    data = {
        'menu': menu,
        'title': 'Добавить/изменить квартиру',
        'form': form,
    }
    return render(request, 'tsj/create.html', data)


def delete_request(request, request_id):
    Request.objects.get(pk=request_id).delete()
    return redirect('requests')


def delete_address(request, address_id):
    Address.objects.get(pk=address_id).delete()
    return redirect('addresses')


def delete_worker(request, worker_id):
    Worker.objects.get(pk=worker_id).delete()
    return redirect('workers')


def delete_resident(request, resident_id):
    Worker.objects.get(pk=resident_id).delete()
    return redirect('residents')


def delete_apartment(request, apartment_id):
    Worker.objects.get(pk=apartment_id).delete()
    return redirect('apartments')


def show_request(request, req_id):
    return HttpResponse("список заявок за счёт жильцов")


def show_addresses(request):
    addresses = Address.objects.all()
    number_of_addresses = Address.objects.count()
    data = {
        'title': "Адреса обслуживания",
        'menu': menu,
        'items': addresses,
        'number': number_of_addresses,
    }
    return render(request, 'tsj/list_addresses.html', context=data)


def show_apartmennnnnts(request):
    page = int(request.GET.get('page', 1))
    per_page = 40
    start_index = (page - 1) * per_page
    end_index = start_index + per_page
    data = Apartment.objects.all()[start_index:end_index].values()
    return JsonResponse({'data': list(data)})


def show_apartments(request):
    apartments = Apartment.objects.all()
    number_of_apartments = Apartment.objects.count()
    p = Paginator(apartments, 30)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    data = {
        'title': "Список квартир",
        'menu': menu,
        'items': page_obj,
        'number': number_of_apartments,
    }
    return render(request, 'tsj/list_apartments.html', context=data)


def show_work_types(request, work_position_id):
    work_pos = get_object_or_404(WorkPosition, id=work_position_id)
    work_types = WorkType.objects.filter(work_position_id=work_position_id)
    data = {
        'title': f"Должность: {work_pos.title}",
        'menu': menu,
        'items': work_types,
    }

tsjrequests/tsj/templates/tsj/create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <p><button type="submit">Отправить</button></p>
</form>

<!--<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
  $(document).ready(function () {
    $('#id_address').change(function () {
      var address = $(this).val();
      $.ajax({
        url: '/ajax-update/',
        data: {'apartment': address},
        dataType: 'json',
        success: function (data) {
          var apartments = data.apartment;
          var select = $('#id_apartment_id');
          select.empty();
          $.each(JSON.parse(data.apartment), function (index, item) {
            select.append('<option value="' + item + '">' + item.fields.number + '</option>');
          });
        }
      });
    });
  });
</script>-->
{% endblock %}

tsjrequests/tsj/templates/tsj/index.html
{% extends 'base.html' %}

{% block content %}
<table class="table">
    {% for i in items %}
    <tr>
        <td>{{ i.title }}</td>
        <td>{{ i.price }} руб.</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tsjrequests/tsj/templates/tsj/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tsjrequests/tsj/templates/tsj/list_addresses.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество адресов: {{ number }}</h4>
<br>
<a href="{% url 'create_address' %}" class="add_link">+ Добавить адрес</a>
<br>
<br>
<br>
<table class="table">
    <tr>
        <th>Улица</th>
        <th>Номер дома</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    <tr>
        <td>{{ i.street_name }}</td>
        <td>{{ i.house_number }} </td>
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_address' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tsjrequests/tsj/templates/tsj/list_apartments.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество квартир: {{ number }}</h4>
<br>
<a href="{% url 'create_apartment' %}" class="add_link">+ Добавить квартиру</a>
<br>
<br>
<br>
<span>
    {% if items.has_previous %}
    <a href="?page=1">&laquo; в начало...</a>
    <a href="?page={{ items.previous_page_number }}">пред.</a>
    {% endif %}
    <span>
        Страница {{ items.number }} из {{ items.paginator.num_pages }}
    </span>
    {% if items.has_next %}
    <a href="?page={{ items.next_page_number }}">след.</a>
    <a href="?page={{ items.paginator.num_pages }}">...в конец &raquo;</a>
    {% endif %}
</span>
<br>
<br>
<table class="table">
    <tr>
        <th>id</th>
        <th>Адрес</th>
        <th>Номер квартиры</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    <tr>
        <td>{{ i.id }}</td>
        <td>{{ i.address }}</td>
        <td>{{ i.number }} </td>
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_apartment' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
<span>
    {% if items.has_previous %}
    <a href="?page=1">&laquo; в начало...</a>
    <a href="?page={{ items.previous_page_number }}">пред.</a>
    {% endif %}
    <span>
        Страница {{ items.number }} из {{ items.paginator.num_pages }}
    </span>
    {% if items.has_next %}
    <a href="?page={{ items.next_page_number }}">след.</a>
    <a href="?page={{ items.paginator.num_pages }}">...в конец &raquo;</a>
    {% endif %}
</span>
<!--<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    var page = 1;
    var loading = false;

    function loadMoreData() {
        if (loading) {
            return;
        }

        var scrollTop = $(window).scrollTop();
        var windowHeight = $(window).height();
        var documentHeight = $(document).height();

        if (scrollTop + windowHeight >= documentHeight - 100) {
            loading = true;
            $.ajax({
                url: '/apartments/',
                data: {'page': page},
                dataType: 'json',
                success: function (data) {
                    if(data.data.length > 0) {
                        console.log(data.data);
                        page++;
                    }
                },
                complete: function () {
                    loading = false;
                }
            });
        }
    }

    $(document).ready(function () {
        $(window).scroll(loadMoreData);
    });
</script>-->
{% endblock %}

tsjrequests/tsj/templates/tsj/list_requests.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество заявок: {{ number }}</h4>
<br>
<a href="{% url 'create_request' %}" class="add_link">+ Добавить заявку</a>
<br>
<br>
<br>
<h4>Фильтр: </h4>
<ul>
    <li><a href="{% url 'requests' %}">Все заявки</a></li>
    <li><a href="{% url 'request_type' 'tsj-request' %}">За счёт ТСЖ</a></li>
    <li><a href="{% url 'request_type' 'resident-request' %}">За счёт жильцов</a></li>
</ul>
<table class="table">
    <tr>
        <th>Тип услуги</th>
        <th>Стоимость</th>
        <th>Назначенный работник</th>
        <th>Житель</th>
        <th>Адрес</th>
        <th>Квартира</th>
        <th>Статус заявки</th>
        <th>Тип заявки</th>
        <th>Дата и время создания</th>
        <th>Дата и время обновления</th>
        <th>Описание или комментарий</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    {% if i.work_type.price == max_price %}
    <tr style="background-color:#ffe22b">
        {% else %} <tr> {% endif %}
        <td>{{ i.work_type }}</td>
        <td>{{ i.work_type.price }} руб.</td>
        {% if i.worker == null %}
        <td>-</td>
        {% else %}
        <td>{{ i.worker }}</td>
        {% endif %}
        <td>{{ i.resident }}</td>
        <td>ул. {{ i.apartment.address }}</td>
        <td>{{ i.apartment.number }}</td>
        <td>{{ i.status }}</td>
        <td>{{ i.request_type }}</td>
        <td>{{ i.create_time }}</td>
        <td>{{ i.update_time }}</td>
        {% if i.description == null %}
        <td>-</td>
        {% else %}
        <td>{{ i.description }}</td>
        {% endif %}
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_request' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tsjrequests/tsj/templates/tsj/list_residents.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество жителей: {{ number }}</h4>
<br>
<a href="{% url 'create_resident' %}" class="add_link">+ Добавить жителя</a>
<br>
<br>
<br>
<table class="table">
    <tr>
        <th>Имя</th>
        <th>Адрес проживания</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    <tr>
        <td>{{ i.first_name }} {{ i.last_name }}</td>
        <td>ул. {{ i.apartment }} </td>
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_resident' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tsjrequests/tsj/templates/tsj/list_work_types.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество услуг: {{ number }}</h4>
<br>
<a href="{% url 'create_resident' %}" class="add_link">+ Добавить жителя</a>
<br>
<br>
<br>
<table class="table">
    <tr>
        <th>Имя</th>
        <th>Адрес проживания</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    <tr>
        <td>{{ i.first_name }} {{ i.last_name }}</td>
        <td>ул. {{ i.apartment }} </td>
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_resident' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tsjrequests/tsj/templates/tsj/list_workers.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<h4>Количество работников: {{ number }}</h4>
<br>
<a href="{% url 'create_worker' %}" class="add_link">+ Добавить работника</a>
<br>
<br>
<br>
<h4>Фильтр: </h4>
<ul>
    <li><a href="{% url 'workers' %}">Все работники</a></li>
    <li><a href="{% url 'worker_position' 'plumbers' %}">Сантехники</a></li>
    <li><a href="{% url 'worker_position' 'electricians' %}">Электрики</a></li>
    <li><a href="{% url 'worker_position' 'janitors' %}">Дворники</a></li>
    <li><a href="{% url 'worker_position' 'cleaners' %}">Уборщицы</a></li>
</ul>
<table class="table">
    <tr>
        <th>Имя</th>
        <th>Должность</th>
        <th>Опции</th>
    </tr>
    {% for i in items %}
    <tr>
        <td>{{ i.first_name }} {{ i.last_name }}</td>
        <td>{{ i.work_position.title }} </td>
        <td><a href="{{ i.get_absolute_url }}" class="update_link">изменить</a><br>
            <a href="{% url 'delete_worker' i.pk %}" class="remove_link">удалить</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}